# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  major : 1
  minor : 0
  offset : 28
  Revision: $[counter(format('{0}.{1}', variables['major'],variables['minor']),0)]
  versionNumber : '$(major).$(minor).$(Revision)'


steps:

- task: PowerShell@2
  displayName: Set the name of the build (i.e. the Build.BuildNumber)
  inputs:
    targetType: 'inline'
    script: |
      [int] $buildIdWithOffset = ([int] $(Revision)) + ([int] $(offset))
      [string] $buildName = "$(major).$(minor).$buildIdWithOffset"
      Write-Host "Setting the name of the build to '$buildName'."
      Write-Host "##vso[build.updatebuildnumber]$buildName"

- script: |
    echo $(buildIdWithOffset)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
