# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  major : 1
  minor : 0
  Revision: $[counter(format('{0}.{1}', variables['major'],variables['minor']),0)]
  versionNumber : '$(major).$(minor).$(Revision)'
name: $(versionNumber)
steps:
- script: echo $(Revision)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
