# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  major : 1
  minor : 1
  x : 1
  y : $[counter(variables['x'], 100)]
 
name: '$(major).$(minor).$(y)'
steps:

# - task: PowerShell@2
#   displayName: Set the name of the build (i.e. the Build.BuildNumber)
#   inputs:
#     targetType: 'inline'
#     script: |
#       [int] $buildIdWithOffset = ([int] $(Revision)) + ([int] $(offset))
#       [string] $buildName = "$(major).$(minor).$buildIdWithOffset"
#       Write-Host "Setting the name of the build to '$buildName'."
#       Write-Host "##vso[build.updatebuildnumber]$buildName"

- script: |
    echo $(y)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
